Provide a solution for issue 250
Raku/problem-solving pull request #271
Opened 2021-03-01 22:34 UTC by Altai-man

A solution for https://github.com/Raku/problem-solving/issues/250

For the curious, I already did:

- [x] Trial & Error way prepared the actually working list of categories
- [x] Wrote a test and then looked at and mostly edit _every_ index entry in our documentation (it is twice the painful it sounds like) to adhere to the rules suggested
- [x] Investigated at least 6 ways of Documentable to be mostly wrong about categories
- [x] Patch it locally to be both simpler and saner

I see this (establishing the guildeline, patching our tooling, doc sources and going to the next pressing issue in the list urgently) as maybe the only real way to move forward we have, hence the work done and mostly ready to be deployed.

ping @patrickbkr

2021-03-02 06:24 UTC, JJ approved these changes
Looks fine, except for a couple of clarifications.

2021-03-02 06:24 UTC, JJ commented on solutions/documentation/search-categories.md
> +where the `$category` variable *explicitly* sets the category and
Maybe you want to say $category-x here? Or just the values in the second and fourth form?

2021-03-02 06:24 UTC, JJ commented on solutions/documentation/search-categories.md
> +
So maybe you mean `$category` and `$category-1`?

2021-03-02 06:24 UTC, JJ commented on solutions/documentation/search-categories.md
> +* A solid state of search categories makes it easier for the contributor to index items into correct
How solid? No procedure to create new categories if needed?

2021-03-02 10:40 UTC, patrickbkr requested changes
This looks very good. I mostly just added questions to help me make sure I understand the proposal correctly.

2021-03-02 10:40 UTC, patrickbkr commented on solutions/documentation/search-categories.md
> +  of category `entry1` will be created of hardcoded kind `Syntax`)
What does "kind `Syntax`" mean? Can you clarify?

2021-03-02 10:40 UTC, patrickbkr commented on solutions/documentation/search-categories.md
> +X<|$category,term>
`$category` is a placeholder for the actual category. Does one need to prefix a "$" to the category name in real code?

2021-03-02 10:40 UTC, patrickbkr commented on solutions/documentation/search-categories.md
> +X<|term>
It is possible to add a term to the index without specifying a category. What category would such a term be assigned? If I understood correctly the goal is to not keep the crazy logic of guessing categories that you explained above.

2021-03-02 10:40 UTC, patrickbkr commented on solutions/documentation/search-categories.md
> +- [ ] `Asyncronous Phasers`
That should be "Asynchronous Phasers". (Note the "h".)

2021-03-02 10:40 UTC, patrickbkr commented on solutions/documentation/search-categories.md
> +      `Metaoperators`, `Postfix operators`, `Prefix operators`, `Circumfix operators`)
Just to make sure I understand this correctly: The categories you listed in parenthesis are also added as valid categories. They are just listed like this, because they are related to the `Operators` category. Right? So one should use the `Operators` category only for terms that don't fit in any of the other categories, right?

2021-03-02 10:40 UTC, patrickbkr commented on solutions/documentation/search-categories.md
> +X<text|$category-1,term-1;...;$category-N,term-N>
Making sure I get it right: We never allow nesting of categories, so subcategories are forbidden. There can never be: `$category-1,$subcategory-1,term-1`. Correct?

2021-03-03 21:15 UTC, Altai-man commented on solutions/documentation/search-categories.md
> +where the `$category` variable *explicitly* sets the category and
Changed to
```
where the `$category-1`, ... `$category-N` variables *explicitly* set the category
for the corresponding term indexed and strictly refer to one of the supported
categories described in this document (including possible future extensions), see the next step.
```

2021-03-03 21:15 UTC, Altai-man commented on solutions/documentation/search-categories.md
> +
Yes, `$category-1`, `$category-2`, ... `$category-N`,, posted the updated chunk above.

2021-03-03 21:28 UTC, Altai-man commented on solutions/documentation/search-categories.md
> +* A solid state of search categories makes it easier for the contributor to index items into correct
I added an appendix explaining how it should work "In My Opinion".

2021-03-03 21:37 UTC, Altai-man commented on solutions/documentation/search-categories.md
> +  of category `entry1` will be created of hardcoded kind `Syntax`)
This is Documentable-y thing, I'll clarify. Added a couple of paragraphs describing this, copy-pasting it here to ease re-review:

```
...
Current Raku documentation organization layout consists of six types of pages,
these include primary pages:

* Explaining various aspects of the language itself, so assigned kind `Language`
* Describing existing types included in the language, so assigned kind `Type`
* Describing various topics around working with the language, so assigned kind `Program`

As well as secondary pages, generated based on the primary pages:

* Explaining routines (subroutines, methods, submethods) provided, so assigned kind `Routine`
* Explaining syntax, so assigned kind `Syntax`
* Describing various concepts the documentation refers to, so assigned kind `Reference`

To assign a category to search item, these ways currently exist:

...
```

2021-03-03 21:49 UTC, Altai-man commented on solutions/documentation/search-categories.md
> +X<|$category,term>
Added a better explanation, here is the copy-paste:

```
where the `$category-1`, ... `$category-N` variables *explicitly* set the category
for the corresponding term indexed and strictly refer to one of the supported
categories described in this document (including possible future extensions), see the next step.

Please, do note that in the example above names such as `$category`, `$category-1` are
used as metasyntactic variables and the actual syyntax does not include the category.

Valid examples are:

``
X<|Syntax,does>
X<|Language,\ (container binding)>
X<Subroutines|Syntax,sub>
X<|Variables,$*PID>
X<Automatic signatures|Variables,@_;Variables,%_>
X<Typing|Language,typed array;Syntax,[ ] (typed array)>
X<Attributes|Language,Attribute;Foreign,Property;Foreign,Member;Foreign,Slot>
``
```

2021-03-03 21:50 UTC, Altai-man commented on solutions/documentation/search-categories.md
> +X<|term>
Sorry, this is just my own miss, a copy-pasto leftover. :(
I removed this sad accident, no more tears, no more fears!

2021-03-03 21:51 UTC, Altai-man commented on solutions/documentation/search-categories.md
> +      `Metaoperators`, `Postfix operators`, `Prefix operators`, `Circumfix operators`)
Exactly, just listed like this because I am lazy. But disregard that, I flatted it out.

2021-03-03 21:58 UTC, Altai-man commented on solutions/documentation/search-categories.md
> +X<text|$category-1,term-1;...;$category-N,term-N>
You are right, never do subcategories. Added a paragraph on this right after this chunk.

I think it (subcategories) makes sense for someone who creates a book in Pod6 (I am still perplexed how it would, but nonetheless) or some over-complicated indexing system, but not for our plain language docs.

The main consumer is the web and there a single category for an entry (don't mix it with many-to-many related tags), is a normal thing to do and what everyone, I hope, expects.

2021-03-04 06:38 UTC, JJ submitted a review, later dismissed
It was good basically in the first iteration, looks fine now. Thanks!

2021-03-04 06:38 UTC, JJ commented on solutions/documentation/search-categories.md
> +X<|$category,term>
Are you sure you want to restrict *all* categories? Or just the first level? It does not make a lot of sense to restrict all of them. Also, Documentable does not really support category-2 and the rest.

2021-03-04 06:38 UTC, JJ commented on solutions/documentation/search-categories.md
> +X<text|$category-1,term-1;...;$category-N,term-N>
I wrote a book in Pod, so why not. So please clarify above about other categories.

2021-03-04 07:50 UTC, patrickbkr commented on solutions/documentation/search-categories.md
> +X<text|$category-1,term-1;...;$category-N,term-N>
@JJ I think I don't understand your request. What do you mean with  "other categories"? Do you mean subcategories (which this proposal explicitly disallows in the context of our language docs)? Or do you refer to categories not found in the authorative list at the end of this document? Or do you ask about categories in the unrelated context of using Pod6 for other things than `docs.raku.org`?  (That would be off topic in this proposal, wouldn't it?)

(Please excuse the list of possibilities above, I don't intend to be rude. I just suspect there might be a lot of potential for misunderstanding each other in the request. So I better be extra explicit.)

2021-03-04 07:57 UTC, JJ commented on solutions/documentation/search-categories.md
> +X<text|$category-1,term-1;...;$category-N,term-N>
Categories in other levels. Edited to say so.

2021-03-04 07:57 UTC, patrickbkr commented on solutions/documentation/search-categories.md
> +X<text|$category-1,term-1;...;$category-N,term-N>
@JJ Pondering on this a bit more. I'm still confused. In my understanding this proposal exclusively talks about rules and procedures to organize categories and indexing for the official Raku documetation. No rules or restrictions are imposed on any other text written in Pod6. Am I mistaken?
To me it sounds like you are concerned that the rules this proposal sets will hinder using Pod6 in other contexts. Which in my understanding this proposal does not at all.

2021-03-04 08:02 UTC, JJ commented on solutions/documentation/search-categories.md
> +X<text|$category-1,term-1;...;$category-N,term-N>
No, not really. But still, we're talking about a spec for indexing documentation for the ages. Right now it would be incredibly cumbersome to add several levels of categories to the JS index we use. But other types of indices might not have that problem. Anyway, the point is that it's not crystal-clear that subcategories are not going to be allowed, which is why you asked for a clarification in the first place. I was addressing what @Altai-man said about writing books in Pod6, which has nothing to do with the main point. Sorry for the distraction.

2021-03-04 08:13 UTC, patrickbkr commented on solutions/documentation/search-categories.md
> +X<text|$category-1,term-1;...;$category-N,term-N>
Ah! So you didn't request for subcategories to be allowed in this proposal. You are talking about all other documents where this proposal doesn't apply. Then it also makes sense that you already approved the PR. Thanks for clarifying!

2021-03-04 08:28 UTC, patrickbkr submitted a review, later dismissed
I approve. The comment is just a wording nit-pick.

2021-03-04 08:28 UTC, patrickbkr commented on solutions/documentation/search-categories.md
> +used as metasyntactic variables and the actual syntax does not include the category.
I'm unsure if there is some deeper meaning I'm missing. But why not:

s/metasyntactic variables and the actual syntax does not include the category/placeholders for an actual category name/ ?

2021-03-04 11:38 UTC, Altai-man commented on solutions/documentation/search-categories.md
> +X<|$category,term>
The intention here is to completely forbid subcategories (we don't actually use it anyway), hence we don't need to think about restrictions for them, they simply don't exist under this system.

Ah, maybe

>where the `$category-1`, ... `$category-N` variables *explicitly* set the category for the corresponding **terms** indexed and strictly refer to one of the supported categories described in this document

is a correct wording for the one-to-one relation, instead of the

>where the `$category-1`, ... `$category-N` variables *explicitly* set the category for the corresponding **term** indexed and strictly refer to one of the supported categories described in this document

I wrote originally?

2021-03-04 11:40 UTC, Altai-man commented on solutions/documentation/search-categories.md
> +used as metasyntactic variables and the actual syntax does not include the category.
Oh, I surely wrote some nonsense in this sentence, of course "the actual syntax does not include the category" is clearly bogus. I'll edit it later.

2021-03-04 20:59 UTC, Altai-man commented on solutions/documentation/search-categories.md
> +X<text|$category-1,term-1;...;$category-N,term-N>
Added a clarification:

>This document describes a solution chosen for the Raku language
documentation sources to solve its specific range of issues in this
particular field and may or may not apply to other usages of Pod6.

2021-03-04 20:59 UTC, Altai-man commented on solutions/documentation/search-categories.md
> +used as metasyntactic variables and the actual syntax does not include the category.
Done.

2021-03-04 20:59 UTC, Altai-man commented
Now how do I gather all the other reviewers? :)

2021-03-05 07:14 UTC, JJ commented
Well, it can be merged in two weeks if no one else approves it. So let's
wait for them to notice it, or simply wait.

2021-03-05 09:18 UTC, patrickbkr commented
Note, that I'm not part of [the official reviewer list](https://github.com/Raku/problem-solving#reviewers), so my approval doesn't count.
The next step, when following  [the formal process](https://github.com/Raku/problem-solving#acceptance), is to request review from all people in that list.
I think it's a bit sad the process has up to now always been finished by waiting out the two weeks and never by actually being approved by the reviewers. We should probably think about what we can do to change that. But that's unrelated to this PR.

2021-03-05 09:19 UTC, patrickbkr commented
@JJ I can't add the reviewers. Can you?

2021-03-05 09:22 UTC, JJ commented
> @JJ I can't add the reviewers. Can you?

I don't think that's really needed; they are notified automatically and will review/approve if they really wish to do so. WRT the process, if there's no consensus it goes to the RSC. I don't think we need any more layers of approval or review.

2021-03-05 09:22 UTC, JJ submitted a review, later dismissed

2021-03-05 09:34 UTC, patrickbkr commented
> I don't think that's really needed; they are notified automatically and will review/approve if they really wish to do so. WRT the process, if there's no consensus it goes to the RSC. I don't think we need any more layers of approval or review.

I'm a bit confused.

What's wrong with notifying the reviewers? (IIU the process correctly, that's what we should do.)
I didn't want to add any more layers of review. I just think it's kind of sad (in the literal sense, mostly for the PR creator) that the process usually isn't finished by approving reviews, but by sitting out two weeks. And then the two weeks are only meant as an escape latch in the case we can't manage to get the PR approved earlier.

Can you clarify?

2021-03-05 10:01 UTC, JJ commented
The reviewers have *already* been notified, all "project owners" are reviewers, and have been notified of the PR, and all our comments to boot.
That some reviewers don't actually review is neither sad nor joyful. Some of them have certain "specialties" (infra, ecosystem) and don't really care about other things. They have limited bandwidth, and they need to focus on what's really their concern. This, meaning docs, is actually *my* concern so it would be sad if *I* wouldn't have cared about it (but in other cases, I would perfectly understand. We're all volunteers, and have to juggle this with family and jobs). I would *really* appreciate if the other reviewers give valuable feedback to this PR, but I understand if they don't.

2021-03-05 10:14 UTC, patrickbkr commented
Huh? Then we should really change the problem-solving process, which currently states (emphasis mine):

> ## Acceptance
> 
> **A review is requested from all of the reviewers** (see
> [the list](#reviewers)). This step exists to ensure peer-review and to
> notify the devs of the major upcoming changes. By approving a PR the
> dev confirms that they reviewed and understood the proposal, and that
> they are OK with it. This is also the last chance to express concerns
> and present feedback (though it is encouraged to do that before this
> step is reached).
> 
> It is expected that **all reviewers will understand** the reasoning of the
> solution and in the end **all of them will approve the PR**. This may
> require time, discussion, and minor adjustments, but if it happens
> that the discussion doesn't lead to mutual understanding, the BDFL may
> step in.
> 
> This is the final step. Once the PR is merged, it is expected that
> corresponding efforts (e.g. PRs in other repos) are merged too, and
> the future work is already outlined. This is the last step.
> 
> 
> 
> ## Edge cases and other notes
> 
> ...
> 
> * Assignees are allowed to call for a “shortcut” to any problem, in
>   which case the solution is applied directly without going through
>   the whole process.
> * If a reviewer does not respond in 14 days, they are **removed from
>   the list of reviewers on that PR**.
> 

I think we should move this discussion somewhere else. I'll create a separate issue.

2021-03-06 21:04 UTC, MasterDuke17 commented on solutions/documentation/search-categories.md
> +- [ ] `Listop operators`
Why 'Listop' instead of just 'List'? I recognize 'listop' is a term currently used, but it doesn't fit with the other operator categories which are of style '<type> operators'.

2021-03-06 21:05 UTC, MasterDuke17 commented on solutions/documentation/search-categories.md
> +- [ ] `Operators`
What about 'Postcircumfix' operators?

2021-03-06 21:06 UTC, MasterDuke17 commented on solutions/documentation/search-categories.md
> +- [ ] `Regexes` (everything related to regex)
I realize we don't want the list to get too big, but I'm kind of surprised there's no 'Grammar' category.

2021-03-06 21:07 UTC, MasterDuke17 approved these changes

2021-03-07 08:31 UTC, JJ commented on solutions/documentation/search-categories.md
> +- [ ] `Regexes` (everything related to regex)
Grammar, as in Raku's Grammar or as in "this is part of the language grammar"? That case is covered by Syntax, I think.

2021-03-07 08:31 UTC, JJ commented on solutions/documentation/search-categories.md
> +- [ ] `Operators`
Well, they're more like "parentheses" than operators, but they are literally operators, so...

2021-03-07 08:31 UTC, JJ commented on solutions/documentation/search-categories.md
> +- [ ] `Listop operators`
Right, good one...

2021-03-07 09:13 UTC, Altai-man commented on solutions/documentation/search-categories.md
> +- [ ] `Listop operators`
>Why 'Listop' instead of just 'List'?

Because I am a dummy, that's why. :)

2021-03-07 09:55 UTC, Altai-man commented on solutions/documentation/search-categories.md
> +- [ ] `Operators`
Added, somehow missed to copypaste it from the implementation.

2021-03-07 09:57 UTC, Altai-man commented on solutions/documentation/search-categories.md
> +- [ ] `Regexes` (everything related to regex)
Most of the things related to grammars (tokens, rules etc) are applicable to regexes, and a tiny bit of things (actual "grammar" declarator, for example) falls into "language", "syntax" and such categories.

2021-03-07 10:06 UTC, Altai-man commented
Update:

- Replaced `Listop operators` with `List operators`
- Added wrongly missing `Postcircumfix operators`

2021-03-07 10:10 UTC, lizmat approved these changes

2021-03-07 14:22 UTC, MasterDuke17 commented on solutions/documentation/search-categories.md
> +- [ ] `Regexes` (everything related to regex)
Raku's Grammar. I realize there is a lot of overlap between 'Regexes' and 'Grammars', but grammars have consistently been advertised as one of Raku's (unique) strengths, and I would be surprised to come to the docs and not see that word pretty front-and-center.

2021-03-07 17:56 UTC, Altai-man commented on solutions/documentation/search-categories.md
> +- [ ] `Regexes` (everything related to regex)
I don't want to be rude here, but I don't think it makes sense in terms of organization.
For example, concurrency is also one of the promoted features, but we don't have the "Concurrency" category.
I can be easily convinced by example:s say there are at least 20 items fitting into this category only and I will be glad to update my code.

2021-03-07 18:51 UTC, JJ commented on solutions/documentation/search-categories.md
> +- [ ] `Regexes` (everything related to regex)
I don't think there are enough concepts to merit a separate category, either. It does have its own tutorials, but that does not mean it will also need a category.

2021-03-07 19:58 UTC, Altai-man commented
So I was fixing things in Documentable again and there is that old bug when some routine has a method form, but in search you only see `method` and it is kind of wrong.
So.... As we now do a difference between `Subroutines` and `Methods`, we can as well introduce `Routines` (which implies both) and phew, problem solved.

Am I updating the proposal with it?

2021-03-08 07:10 UTC, JJ approved these changes

2021-03-08 07:16 UTC, JJ commented
> So I was fixing things in Documentable again and there is that old bug when some routine has a method form, but in search you only see `method` and it is kind of wrong.
> So.... As we now do a difference between `Subroutines` and `Methods`, we can as well introduce `Routines` (which implies both) and phew, problem solved.
> 
> Am I updating the proposal with it?

As a matter of fact, we have all three, IIRC. So it's probably better to merge them into one... That, however, opens a whole new can of worms. What about `termp`s? Aren't operators actually other kind of routines? Now we have `postcircumfix` and other kind of operators as part of the first-class categories. Shouldn't we make them routines and that's that?

2021-03-08 09:58 UTC, Altai-man commented
>What about terms?

Terms have their own category.

>Aren't operators actually other kind of routines?

Technically - yes, from the point of categorization view - no, operators are operators, things to call are things to call.

>Shouldn't we make them routines and that's that?

This will introduce clashes. The reason why I introduced separate first-level categories for operator types is because `+` can be infix and can be prefix, so the search anchors to both of them clash, nobody wants to have two `Routines, +` and `Routines, +` in their search and having to guess what is what.

2021-04-11 16:25 UTC, Altai-man commented
Just updated it adding `Routines` as I suggested above, a really handy thing.

2021-04-11 17:49 UTC, JJ approved these changes

2021-04-11 22:01 UTC, Altai-man commented
Since the acceptance policy does not work, I will force merge it after the documentation team will be assembled AND given the website replacement actually happens.

2021-04-17 19:15 UTC, merged